### ISSUE TITLE
"Page not found" problem when used together with ColdTricks group_tools plugin

### ISSUE THREAD

**Issue by schmidtwastl** [juho-jaakkola/elgg-group_requests#1]
Your plugin works great for me on a vanilla install. 
When additionally using group_tool plugin from ColdTrick everything works fine until the admin clicks on groups/requests. (where all the pending requests should be listed).
Then an error shows up: 
"Page not found
Sorry. We could not find the page that you requested."

Link to group_tools plugin: https://github.com/ColdTrick/group_tools

**Comment by juho-jaakkola** [comment]
They both use `groups/request` in the URL https://github.com/ColdTrick/group_tools/blob/master/lib/hooks.php#L86

Not sure yet if either one has a bug.

**Comment by schmidtwastl** [comment]
Thanks for the hint! Independently they both work fine. 
I tried a fast fix for my case by changing all strings 'groups/requests' to 'groups/pendingrequests' so that they don´t use the same URL. But I messed something up. I will give it another try, when I have the time to try it with a more sophisticated approach

**Comment by juho-jaakkola** [comment]
Try also changing the order of the plugins. (Although in the end the `groups/request` page needs to be changed in either one in order to use them simultaneously.)

**Comment by jdalsem** [comment]
@juho-jaakkola is it an idea to add this feature into the group_tools plugin?

**Comment by juho-jaakkola** [comment]
I prefer plugins to do only a single task. Putting too many features to a single plugin is usually a bad idea in the long run.

**Comment by juho-jaakkola** [comment]
It seems this issue has in fact been fixed in a831e282b85ddd12ddbcf21588a105a730071a12.
